package com.loiane.java.aula52;

public class UsandoMinhaException {

	public static void main(String[] args) {
		
		int[] numeros = {4, 8, 16, 32, 64, 128};
		int[] denominador = {2, 0, 4, 8, 0, 2, 4};
		
		for (int i = 0; i < numeros.length; i++){
			try {
				if (numeros[i] % 2 != 0){
					//Lançar minha exception
					throw new Exception("Número ímpar, divisão não exata.");
				}
				
				System.out.println(numeros[i] + " / " + denominador[i] + " = " 
						+ (numeros[i]/denominador[i]));
			}
			catch (ArithmeticException | ArrayIndexOutOfBoundsException exception){
				System.out.println("Ocorreu um erro");
			}
			// este catch referente ao throw new
			catch (Exception exception){
				System.out.println("Ocorreu um erro");
				System.out.println(exception.getMessage());
				
			}
			
		}	

	}

}
